# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |xixihaha1995.github.io| "https://github.com/xixihaha1995/xixihaha1995.github.io.git" }
gem "github-pages", "~>214", group: :jekyll_plugins

# gem "rails"
